### ISSUE TITLE
support keywords for search

### ISSUE THREAD

**Issue by matthiasclasen** [flathub/linux-store-frontend#123]
I've noticed a few unexpected search results, e.g. anydesk not showing up in a search for "remote" despite the description containing that term. An easy way to fix up such cases would be keywords

**Comment by wjt** [comment]
I had a quick look to see how easy it'd be to use the keywords from appstream and the answer was “not as easy as I'd hoped”.

First, the i18n bit. The AppdataComponent object for each app points to a Component which holds [one](https://github.com/jgarciao/appstream-appdata-java/blob/master/src/main/java/org/freedesktop/appstream/appdata/Component.java#L100-L101) [Keywords object](https://github.com/jgarciao/appstream-appdata-java/blob/master/src/main/java/org/freedesktop/appstream/appdata/Keywords.java) which I think corresponds to the first `<keywords>` element found. Checking the [appstream spec](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-keywords), there can actually be more than one `<keywords>` element with different `lang=`.

Anyway this is theoretical because every app on Flathub has a single unlocalized `<keywords>`.

Right now search on the site is implemented by [fetching the JSON description of every app and iterating it](https://github.com/flathub/linux-store-frontend/blob/3017b4d7e2ddde9136e785566e3f1eac330a4947/src/app/linux-store-api.service.ts#L103-L115). The function has "keywords" in its name but the AppStream keywords are not provided in the JSON description or indeed stored in the database. So basically one needs to duplicate all the handling of categories (new database table, many-to-many join, and mapping from that to JSON list of strings), and then make the frontend search that string.

(Better would be to do search on the server-side and build an index. One could consider also matching on app descriptions, but considering those to be lower-quality hits.)

**Comment by barthalion** [comment]
This should be working now with the new backend.
