### ISSUE TITLE
API returns 502, resulting in broken detail pages for some apps

### ISSUE THREAD

**Issue by lazka** [flathub/linux-store-frontend#154]
See https://github.com/flathub/flathub/issues/725

Example:

* https://flathub.org/apps/details/org.gottcode.Connectagram
* https://flathub.org/api/v1/apps/org.gottcode.Connectagram

**Comment by jgarciao** [comment]
https://status.flathub.org/ shows that the backend is down. @ramcq, could
you take a look?


El dia 17 de nov. 2018 15:38, "Christoph Reiter" <notifications@github.com>
va escriure:

See flathub/flathub#725 <https://github.com/flathub/flathub/issues/725>

Example:

   - https://flathub.org/apps/details/org.gottcode.Connectagram
   - https://flathub.org/api/v1/apps/org.gottcode.Connectagram

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flathub/linux-store-frontend/issues/154>, or mute the
thread

**Comment by jgarciao** [comment]
The backend server is working properly again. Sorry for the inconvenience
