### ISSUE TITLE
Flathub pages not appearing as Google search results (SEO)

### ISSUE THREAD

**Issue by allanday** [flathub/linux-store-frontend#175]
If I search in Google for "android studio flatpak", I don't get any results for the Flathub Android Studio page ( https://flathub.org/apps/details/com.google.AndroidStudio ). What I do get is a top hit for https://github.com/flathub/com.google.AndroidStudio which, as a user, is not very helpful.

I think we can assume that, for many users, Google is the first port of call in trying to find apps to install, so it's important that apps on Flathub appear there.

**Comment by jgarciao** [comment]
I made some SEO optimizations last year and most of the app pages are
indexed by Google. If you search "site: flathub.org" you'll see more than
700 pages indexed.

If you search for "Spotify Flatpak", "gimp Flatpak", or many other apps on
Google you'll have the Flathub app page as one of the top results

I can look in Google Search Console if the Android Studio page is not
indexed for any reason, but is possible that is not appearing in the search
results because there are not many links from other websites pointing there.

El dc., 17 d’abr. 2019, 18:40, Allan Day <notifications@github.com> va
escriure:

**Comment by jgarciao** [comment]
The service I use to prerender websites for bots (it's necessary to properly index JavaScript based websites) was stuck. 

Afer restarting it and fidling with Google search console your search shows flathub's website as fist result
