### ISSUE TITLE
Show more items on the new & updated page

### ISSUE THREAD

**Issue by razzeee** [flathub/linux-store-frontend#304]
While popular shows 50 items, the new and updated page https://flathub.org/apps/collection/recently-updated only shows the latest 20.

**Comment by haggen88** [comment]
I think that also the new applications should be able to differentiate themselves from the updated ones.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Ideally, the amount that is displayed should be dependent upon the size of the screen, because this shall reduce server load unnecessarily, yet increase it necessarily for massive screens and/or resolutions. This has been implemented by many websites, such as almost all free news websites that display advertisements below their content.
