### ISSUE TITLE
Add a prominent 'beta' label

### ISSUE THREAD

**Issue by allanday** [flathub/linux-store-frontend#62]
Since the web front end is likely to have some rough edges when it's first launched, we should add a prominent 'beta' or 'work in progress' label somewhere. It could be a banner, ribbon or heading, and should be visible from every page.

**Comment by jgarciao** [comment]
This is the best I could do with my inkscape skills. Not prominent but visible

![linux-store-beta](https://user-images.githubusercontent.com/66894/38364961-eb0c9cb4-38da-11e8-8d1e-55b98c28719d.png)

**Comment by jimmac** [comment]
The label is a tad too subtle, perhaps a pill like treatment would be better.

![flathub-beta](https://user-images.githubusercontent.com/14821/38369539-3d8c5eb8-38e8-11e8-9289-38f55d34bbcd.png)

**Comment by jimmac** [comment]
Let me know the nominal dimensions you need this in.

**Comment by jgarciao** [comment]
How does this look to you?

![flathub-beta-new-logo](https://user-images.githubusercontent.com/66894/38382690-e6053336-390a-11e8-91f9-7e3814a1fc17.png)

**Comment by jgarciao** [comment]
I've cropped the image and reduced the size. It looks fine on desktop but not so great on my cellphone. I guess because higher doing

http://45.55.104.129/home


Could you please make an image like mine but with higher quality?

https://github.com/flathub/linux-store-frontend/blob/master/src/assets/themes/flathub/flathub-logo-toolbar-beta.png

**Comment by jimmac** [comment]
Rather than giving you an RGBA PNG, here's an SVG which you can use the same way, but will magically just work on HiDPI displays.

http://jimmac.musichall.cz/stuff/logo-beta.svg
