### ISSUE TITLE
Metadata section alignment issues

### ISSUE THREAD

**Issue by allanday** [flathub/linux-store-frontend#66]
The elements in the metadata section aren't aligned with each other. The result is that the section looks messy and is hard to scan. Layouts like this need to use a grid in order to ensure alignment.

How it looks:

![image](https://user-images.githubusercontent.com/213068/38307885-2cfed2fa-380d-11e8-8b7b-fac279834de0.png)

How it looks when you add the alignment points:

![image](https://user-images.githubusercontent.com/213068/38307900-3f160cc4-380d-11e8-9f18-a8e521a3cd13.png)

How it might look if it were grid aligned:

![image](https://user-images.githubusercontent.com/213068/38308038-b67f27f0-380d-11e8-953d-3892a5c8d9a9.png)

**Comment by jgarciao** [comment]
I've put License in its own line because for some apps (for example [builder](http://45.55.104.129/apps/details/org.gnome.Builder)) the value is really long. Also some apps have a lots of categories. How do you want me to deal with this, having two lines?

I could also show the field _In store since_ which is the data when the app was first added to the store. Do you find it useful? Where would you put it?

**Comment by jgarciao** [comment]
The utility of the field _Publisher_ is to know who is publishing this app in Flathub. Right now the only way to know it (I think) is to link to the "contributors" page in the github repo. I don't know if "Flathub administrators" is the best fit for this meaning

**Comment by jgarciao** [comment]
About the License field I have also simplified in Free/Propietary
